spring:
  application:
    name: todo-api
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
